services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: 'clickhouse-server'
    hostname: clickhouse
    mem_limit: 8G
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
    environment:
      - CLICKHOUSE_PASSWORD=Helpforkiat@123
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./clickhouse:/var/lib/clickhouse
      - ./clickhouse-logs:/var/log/clickhouse-server
      - ./clickhouse-config:/etc/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      'MB_HTTP_TIMEOUT': '5000'
      'JAVA_TIMEZONE':   'UTC'
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./metabase-data:/metabase-data
      - ./metabase/plugins:/app/plugins
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: postgres
      MB_DB_PASS_FILE: admin123
      MB_DB_HOST: postgres

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d metabase -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql
    restart: unless-stopped
